# Generated by Django 5.2.3 on 2025-07-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
