# Generated by Django 5.2.3 on 2025-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='matricula',
        ),
        migrations.AddField(
            model_name='avion',
            name='columnas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='avion',
            name='filas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='avion',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
