# Generated by Django 5.2.3 on 2025-07-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_avion_matricula_avion_columnas_avion_filas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vuelo', 'En Vuelo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.avion')),
            ],
        ),
    ]
