# Generated by Django 5.2.3 on 2025-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='aviones/'),
        ),
    ]
