# Generated by Django 5.2.3 on 2025-08-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('avion', 'numero', 'fila', 'columna')},
        ),
    ]
