# Generated by Django 5.2.3 on 2025-08-01 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_asiento_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
