# Generated by Django 5.2.3 on 2025-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_pasajero_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
