# Generated by Django 5.2.3 on 2025-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_pasajero_email_pasajero_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('economico', 'Económico'), ('premium', 'Premium Economy'), ('ejecutivo', 'Ejecutivo'), ('primera', 'Primera Clase')], max_length=20),
        ),
    ]
