# Generated by Django 5.2.3 on 2025-08-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_asiento_estado_alter_asiento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='gestion.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
