# Generated by Django 5.2.3 on 2025-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_reserva_asiento_alter_reserva_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
