# Generated by Django 5.2.3 on 2025-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_reserva_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asiento',
        ),
        migrations.AddField(
            model_name='asiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='asientos',
            field=models.ManyToManyField(blank=True, related_name='reservas', to='gestion.asiento'),
        ),
    ]
