# Generated by Django 5.2.3 on 2025-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_reserva_asiento_asiento_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='enviado_por_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='estado',
            field=models.CharField(choices=[('emitido', 'Emitido'), ('cancelado', 'Cancelado'), ('verificado', 'Verificado')], default='emitido', max_length=20),
        ),
    ]
